spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      allow.auto.create.topics: false
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      allow.auto.create.topics: false
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.poc.springkafkapoc.data"
test:
  topic: quickstart-events
  topicDLT: quickstart-events-DLT